Regular update
Update .bashrc
Update .gitconfig
Update .local/bin/cscc_work
Add .local/bin/lazygit
Update .local/bin/toggle-adguardhome.sh
Update .zshrc
Update .ssh/config
Update .local/bin/cscc_work
Remove .local/bin/lazygit
Add .local/bin/lazygit

diff --git a/dot_local/bin/executable_cscc_work b/dot_local/bin/executable_cscc_work
--- a/dot_local/bin/executable_cscc_work
+++ b/dot_local/bin/executable_cscc_work
@@ -2,6 +2,28 @@
 
 # exit if encounter any error
 set -e
+# set -x
+
+ERR_GENERIC=1
+ERR_USER_INT=2
+
+ErrorHandling () {
+    if [ $? -ne 0 ]
+    then 
+        error "exit with error, stop the VPN"
+        vpn_string=""
+        get_vpn_status -s "$TEST_MODE" && vpn_string="$TEST_MODE"
+        get_vpn_status -s "$PRODUCTION_MODE" && vpn_string="$PRODUCTION_MODE"
+        # ask whether disconnect VPN
+        if [ -n "$vpn_string" ]; then
+            stop_all_vpn -s || true
+            exit $ERR_GENERIC
+        fi
+    fi
+    exit $ERR_USER_INT
+}
+# stop vpn for any interrupt
+trap ErrorHandling EXIT SIGINT SIGTERM SIGQUIT
 
 # CONSTANTS(names)
 TEST_MODE="test"
@@ -13,7 +35,8 @@ DEBUG=4
 
 # config variables
 LOG_LEVEL=${LOG_LEVEL:-$INFO}
-CONFDIR="~/.config/cscc/"
+# LOG_LEVEL=${LOG_LEVEL:-$DEBUG}
+CONFDIR="$HOME/.config/cscc/"
 CONF="$CONFDIR/config.json"
 # VPN timeout interval and timeout
 TIMEINTERVAL=0.1 # 100ms
@@ -23,28 +46,43 @@ TIMEOUT=150      # 15s
 fortivpn_invoke(){
     local operation="$1"
     local vpn_type="$2"
+    local vpn_string vpn_interface
+    vpn_string=$(get_vpn_string)
+    vpn_interface=$(get_vpn_interface $vpn_string)
 
     if [ $operation != "start" ] && [ $operation != "stop" ]; then
-        error "Invalid operation: $operation, exiting..." && exit 1
+        error "Invalid operation: $operation, exiting..." && exit $ERR_GENERIC
     fi
 
     if [ "$operation" == "stop" ]; then
         # clear dns setting for systemd-resolved bug(don't clear resolv.conf 
         # setting)
-        sudo resolvectl revert ppp0
+        sudo resolvectl revert "$vpn_interface"
     fi
 
     if sudo systemctl "$operation" "openfortivpn@cscc_$vpn_type.service"; then
         if [ "$operation" == "start" ]; then
-            for i in $(seq 10); do
+            for _ in $(seq 10); do
                 get_vpn_status "$vpn_type" | grep -q 'healthy' && break
                 sleep 1
             done
         fi
         debug "$vpn_type VPN is $(get_vpn_status "$vpn_type")"
     else
-        error "$vpn_type VPN $operation failed, exiting..." && exit 1
+        error "$vpn_type VPN $operation failed, exiting..." && exit $ERR_GENERIC
     fi
+}
+
+get_vpn_string() {
+    local vpn_string
+    if get_vpn_status -s "$TEST_MODE"; then
+        vpn_string="$TEST_MODE"
+    fi
+    if get_vpn_status -s "$PRODUCTION_MODE"; then 
+        vpn_string="$PRODUCTION_MODE"
+    fi
+    echo "$vpn_string"
+    return 0
 }
 
 log(){
@@ -55,11 +93,10 @@ log(){
     local timestamp=$(date +"%Y-%m-%d %H:%M:%S")
 
     local log_message="[$timestamp] [$log_level_str] - $message"
-    echo "$log_message"
 
-    # if [[ $log_level_int -le $LOG_LEVEL ]]; then
-    #     echo "$log_message"
-    # fi    
+    if [[ $log_level_int -le $LOG_LEVEL ]]; then
+        echo "$log_message"
+    fi    
 }
 
 function error() {
@@ -98,30 +135,34 @@ prompt_help(){
 }
 
 get_vpn_status(){
+    local OPTIND silent vpn_string
     silent=0
-
-    OPTIND=0
-    while getopts ":s" op; do
-        case "$op" in
+    while getopts "s" op; do
+        case $op in
             s)
                 silent=1
                 ;;
+            ?)
+                error "unknown key: $op"
+                ;;
+
             *)
                 error "Invalid option: -${OPTARG}"
-                exit 1
+                exit $ERR_GENERIC
                 ;;
         esac
     done
     shift $((OPTIND-1))
+    vpn_string="$1"
 
-    if systemctl is-active --quiet "openfortivpn@cscc_$1.service"; then
+    if systemctl is-active --quiet "openfortivpn@cscc_$vpn_string.service"; then
         if [ "$silent" -eq 0 ]; then
             local status_string=""
             local dns_server=""
             [ "$1" = "$PRODUCTION_MODE" ] && \
                 dns_server="10.1.1.1" || dns_server="10.2.1.1"
 
-            connectivity_check "$1" > /dev/null && \
+            connectivity_check "$vpn_string" > /dev/null && \
                 status_string="healthy" || status_string="unhealthy"
 
             [ "$status_string" = "healthy" ] && dig @"$dns_server" \
@@ -129,7 +170,7 @@ get_vpn_status(){
                 status_string="healthy" || status_string="degreded(dns failure)"
 
             [ "$silent" -eq 0 ] && \
-                printf 'connected(%s, %s)' "$(get_vpn_ip)" "$status_string"
+                printf 'connected(%s, %s)' "$(get_vpn_ip $vpn_string)" "$status_string"
         fi
         return 0
     else
@@ -138,14 +179,26 @@ get_vpn_status(){
     fi
 }
 
+get_vpn_interface(){
+    local vpn_string;
+    vpn_string="$1"
+    if [[ $vpn_string == "$TEST_MODE" ]]; then
+        echo "ppp0"
+    elif [[ $vpn_string == "$PRODUCTION_MODE" ]]; then
+        echo "ppp1"
+    fi
+}
+
 get_vpn_ip_raw(){
-    ip addr show ppp0 | grep -Po 'inet \K[\d.]+'
+    ip addr show "$1" | grep -Po 'inet \K[\d.]+'
 }
 
 get_vpn_ip(){
+    local target_interface
+    target_interface="$(get_vpn_interface $1)"
     while [ "$TIMEOUT" -gt 0 ]; do
-        if [ "$(get_vpn_ip_raw 2>/dev/null)" != "" ]; then
-            get_vpn_ip_raw 2>/dev/null
+        if [ "$(get_vpn_ip_raw "$target_interface" 2>/dev/null)" != "" ]; then
+            get_vpn_ip_raw "$target_interface" 2>/dev/null
             return 0
         fi
         sleep "$TIMEINTERVAL"
@@ -164,71 +217,149 @@ status(){
 }
 
 stop_all_vpn(){
-    vpn_string=""
-    get_vpn_status -s "$TEST_MODE" && vpn_string="$TEST_MODE"
-    get_vpn_status -s "$PRODUCTION_MODE" && vpn_string="$PRODUCTION_MODE"
+    local OPTIND short_opt silent_enabled vpn_string
+    silent_enabled=""
+    while getopts s short_opt; do
+        case $short_opt in
+            s)
+                # make other command silent
+                silent_enabled="true"
+            ;;
+            *)
+                echo "Usage: stop_all_vpn [-s]"
+                echo "Stop CSCC VPN"
+                echo ""
+                echo "  -s, --silent          silent mode"
+                exit $ERR_GENERIC
+        esac
+    done
+
+    vpn_string="$(get_vpn_string)"
+    if [[ -z "$vpn_string" ]]; then
+        debug "No VPN enabled, just return!!"
+        return
+    fi
+
     # ask whether disconnect VPN
-    if [ -n "$vpn_string" ]; then
+    if [[ -z "$silent_enabled" ]]; then
         warn "$vpn_string VPN is running, check whether user want to stop it..."
         printf "%s VPN(%s) service is running, do you want to disconnect? (Y/n) - " \
-        "$vpn_string" "$(get_vpn_ip)"
+        "$vpn_string" "$(get_vpn_ip vpn_string)"
         read -r answer
         if [ "$answer" != "${answer#[Nn]}" ]; then
            info "answer is \`$answer\` $vpn_string VPN service would not stopped, exiting..."
+           return
         fi
-
-        # stop vpn service
-        info "stopping $vpn_string VPN..."
-        fortivpn_invoke stop "$vpn_string"
     fi
+
+    # stop vpn service
+    info "stopping $vpn_string VPN..."
+    fortivpn_invoke stop "$vpn_string" || true
 }
 
 start_vpn(){
-    # $1 is the VPN type, test or prod
-    vpn_string=""
+    local OPTIND short_opt ignore_enabled vpn_string
+    ignore_enabled=""
+    while getopts 'i' short_opt; do
+        case $short_opt in
+            i)
+                # make other command silent
+                ignore_enabled="true"
+            ;;
+            *)
+                echo "Usage: start_vpn [-s]"
+                echo "Start CSCC VPN"
+                echo ""
+                echo "  -i, --ignore          ignore current VPN status"
+                exit $ERR_GENERIC
+        esac
+        shift
+    done
+    local target_vpn_type="$1"
 
     info "check current used VPN type(if VPN is still running)..."
-    get_vpn_status -s "$TEST_MODE" && vpn_string="$TEST_MODE"
-    get_vpn_status -s "$PRODUCTION_MODE" && vpn_string="$PRODUCTION_MODE"
+    vpn_string="$(get_vpn_string)"
 
-    if [ "$vpn_string" = "$1" ]; then
+    if [ "$vpn_string" = "$target_vpn_type" ]; then
         info "$vpn_string VPN service is running, exiting..." && exit 0
-    elif ! stop_all_vpn; then
-        error "$vpn_string VPN stop failed, exiting..." && exit 1
+    elif ! stop_all_vpn -s; then
+        error "$vpn_string VPN stop failed, exiting..." && exit $ERR_GENERIC
     fi
 
-    [ "$vpn_string" != "" ] && warn "$vpn_string VPN is stopped, check whether wants' to start $1 VPN..."
-    printf "%s VPN service is not running, do you want to start it? (Y/n) - " "$1"
-    read -r answer
-    if [ "$answer" != "${answer#[Nn]}" ]; then
-        info "answer is \`$answer\` VPN service would not not started, exiting..."
-        exit 0
-    else
-        info "answer is \`$answer\` VPN service would start"
+    if [[ -n "$vpn_string" ]]; then
+        warn "$vpn_string VPN is stopped, check whether wants' to start" `
+            ` "$target_vpn_type VPN..."
+    fi
+    if [[ -z $ignore_enabled ]]; then
+        read -r -p "$target_vpn_type VPN service is not running, do you "`
+            `"want to start it? (Y/n) - " answer 
+        if [ "$answer" != "${answer#[Nn]}" ]; then
+            info "answer is \`$answer\` VPN service would not not started, "`
+                `"exiting..."
+            exit 0
+        else
+            info "answer is \`$answer\` VPN service would start"
+        fi
     fi
 
     # start VPN service
-    info "starting $1 vpn..."
-    fortivpn_invoke start "$1"
+    info "starting $target_vpn_type vpn..."
+    fortivpn_invoke start "$target_vpn_type"
 
+    local target_interface
+    target_interface=$(get_vpn_interface $target_vpn_type)
     # setup dns naming service for VPN connection
-    if [ "$1" == "$PRODUCTION_MODE" ]; then
-        sudo resolvectl dns ppp0 10.1.1.1 10.1.1.2
+    if [ "$target_vpn_type" == "$PRODUCTION_MODE" ]; then
+        sudo resolvectl dns $target_interface 10.1.1.1 10.1.1.2
+        sudo resolvectl domain $target_interface '~test.cc.cs.nctu.edu.tw' \
+            '~cc.cs.nctu.edu.tw' '~cs.nctu.edu.tw' '~test.cs.nctu.edu.tw'
+
+        # FIXME: refactor this code, follwoing is duplicated
+
+        # add route to prevent exitnode ruins whole routing table
+        info "tailscale is enabled, add throw at routing table"
+        tailscale_routing_table="$(ip r show table 52)"
+        for cidr in $(ip r show dev $target_interface | cut -f 1 -d' '); do
+            ip_cmd=$(printf 'throw %s' "$cidr")
+            if grep -q "$ip_cmd" <(echo "$tailscale_routing_table"); then
+                debug "table 52 has \`$ip_cmd\`, skipping"
+                continue
+            fi
+            exec_cmd=$(printf "sudo ip route add %s table 52" "$ip_cmd")
+            debug "add $ip_cmd into table 52, exec $exec_cmd"
+            sh -c "$exec_cmd"
+        done
     else
-        sudo resolvectl dns ppp0 10.2.1.1 10.2.1.2 
+        sudo resolvectl dns $target_interface 10.2.1.1 10.2.1.2 
+        sudo resolvectl domain $target_interface '~test.cc.cs.nctu.edu.tw' \
+            '~cc.cs.nctu.edu.tw' '~cs.nctu.edu.tw' '~test.cs.nctu.edu.tw'
+
+        # add route to prevent exitnode ruins whole routing table
+        info "tailscale is enabled, add throw at routing table"
+        tailscale_routing_table="$(ip r show table 52)"
+        for cidr in $(ip r show dev $target_interface | cut -f 1 -d' '); do
+            ip_cmd=$(printf 'throw %s' "$cidr")
+            if grep -q "$ip_cmd" <(echo "$tailscale_routing_table"); then
+                debug "table 52 has \`$ip_cmd\`, skipping"
+                continue
+            fi
+            exec_cmd=$(printf "sudo ip route add %s table 52" "$ip_cmd")
+            debug "add $ip_cmd into table 52, exec $exec_cmd"
+            sh -c "$exec_cmd"
+        done
     fi
     info "set search domain([cc].cs.nctu.edu.tw) for $1 vpn"
     # INFO: for security reason, only set the dns as routing-domain is good
     # check https://systemd.io/RESOLVED-VPNS/ for more information
     #
-    # sudo resolvectl domain ppp0 '~test.cc.cs.nctu.edu.tw' \
-    #     '~cc.cs.nctu.edu.tw' '~cs.nctu.edu.tw' '~test.cs.nctu.edu.tw'
     #
     # INFO: but I set it as search domain just for convenience
-    sudo resolvectl domain ppp0 'test.cc.cs.nctu.edu.tw' 'cc.cs.nctu.edu.tw'
-    sudo resolvectl default-route ppp0 false
+    sudo resolvectl domain $target_interface 'test.cc.cs.nctu.edu.tw' 'cc.cs.nctu.edu.tw'
+    sudo resolvectl default-route $target_interface false
 
-    info "activate $1 VPN connection done"
+    # use original route to 140.113.0.0/16(for latency)
+    ip route add throw 140.113.0.0/16 table 52 2>/dev/null || true
+    info "activate $target_vpn_type VPN connection done"
 }
 
 toggle_vpn(){
@@ -242,7 +373,7 @@ toggle_vpn(){
 
 connectivity_check(){
     local vpn_type="$1"
-    local ping_dst_ip=""; [ $vpn_type == $TEST_MODE ] \
+    local ping_dst_ip=""; [[ $vpn_type == "$TEST_MODE" ]] \
         && ping_dst_ip="10.2.1.1" || ping_dst_ip="10.1.1.1"
 
     info "check $vpn_type VPN health..."
@@ -252,25 +383,14 @@ connectivity_check(){
     info "$vpn_type VPN is healthy"
 }
 
-healthy_check(){
-    # check VPN systemd unit is exist
-    for type in $TEST_MODE $PRODUCTION_MODE; do
-        if ! systemctl list-units --full --all | grep -q "openfortivpn@cscc_$type.service"; then
-            error "$type VPN systemd unit is not exist, exiting..." && exit 1
-        fi
-    done
-
-    # TODO: check VPN password is exist
-}
-
 case "$1" in
     -t|--test)
         info "start test vpn..."
-        start_vpn "test"
+        start_vpn -i "$TEST_MODE"
       ;;
     -p|--production)
         info "start production vpn..."
-        start_vpn "$PRODUCTION_MODE"
+        start_vpn -i "$PRODUCTION_MODE"
       ;;
     -s|--status)
         info "print VPN status..."
@@ -285,6 +405,17 @@ case "$1" in
         info "toggle VPN..."
         toggle_vpn "$TEST_MODE"
       ;;
+    -x|--terminate)
+        info "terminate VPN..."
+        stop_all_vpn -s
+      ;;
+
+    -r|--restart)
+        info "restart VPN"
+        target_vpn_type=$(get_vpn_string)
+        stop_all_vpn -s
+        start_vpn -i "$target_vpn_type"
+    ;;
 
     *)
       # if no arguments are given, print status, else prompt help
@@ -292,11 +423,11 @@ case "$1" in
           info "no arguments given, fallback to toggle VPN..."
           info "print VPN status..."
           status | boxes -p "h2v1"
-          echo 
+          echo ""
           toggle_vpn "$TEST_MODE"
       else
         prompt_help
-        exit 1
+        exit $ERR_GENERIC
       fi
       ;;
 esac
